import { Stock } from './types';

export const MOCK_STOCKS: Stock[] = [
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    price: 189.43,
    change: 1.25,
    changePercent: 0.66,
    marketCap: '2.95T',
    peRatio: '29.4',
    industry: 'Technology',
    description: 'Apple designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide.',
    history: Array.from({ length: 20 }, (_, i) => ({
      time: `${i}:00`,
      price: 185 + Math.random() * 10,
    })),
  },
  {
    symbol: 'TSLA',
    name: 'Tesla, Inc.',
    price: 175.22,
    change: -4.50,
    changePercent: -2.51,
    marketCap: '550B',
    peRatio: '42.1',
    industry: 'Automotive',
    description: 'Tesla designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems.',
    history: Array.from({ length: 20 }, (_, i) => ({
      time: `${i}:00`,
      price: 170 + Math.random() * 15,
    })),
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    price: 875.28,
    change: 12.30,
    changePercent: 1.42,
    marketCap: '2.16T',
    peRatio: '72.8',
    industry: 'Semiconductors',
    description: 'NVIDIA provides graphics, and compute and networking solutions in the United States and internationally.',
    history: Array.from({ length: 20 }, (_, i) => ({
      time: `${i}:00`,
      price: 850 + Math.random() * 50,
    })),
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    price: 415.10,
    change: 2.15,
    changePercent: 0.52,
    marketCap: '3.08T',
    peRatio: '35.2',
    industry: 'Software',
    description: 'Microsoft develops and supports software, services, devices, and solutions worldwide.',
    history: Array.from({ length: 20 }, (_, i) => ({
      time: `${i}:00`,
      price: 400 + Math.random() * 20,
    })),
  },
  {
    symbol: 'AMZN',
    name: 'Amazon.com, Inc.',
    price: 178.15,
    change: -1.20,
    changePercent: -0.67,
    marketCap: '1.85T',
    peRatio: '60.5',
    industry: 'Ecommerce',
    description: 'Amazon engages in the retail sale of consumer products and subscriptions through online and physical stores.',
    history: Array.from({ length: 20 }, (_, i) => ({
      time: `${i}:00`,
      price: 170 + Math.random() * 10,
    })),
  },
  {
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    price: 152.45,
    change: 0.85,
    changePercent: 0.56,
    marketCap: '1.91T',
    peRatio: '25.8',
    industry: 'Internet Media',
    description: 'Alphabet offers Google Search, Ads, Commerce, Maps, YouTube, Google Cloud, Android, Chrome, and Google Play.',
    history: Array.from({ length: 20 }, (_, i) => ({
      time: `${i}:00`,
      price: 145 + Math.random() * 10,
    })),
  }
];
